### ISSUE TITLE
Serialization of nested classes produces faulty JSON

### ISSUE THREAD

**Issue by btcinsight** [g40/esj#1]
If we serialize nested classes (depth of 2 or more), it produces faulty JSON code (a closing '}' is missing)

The code below shows the bug. It produces the following JSON:
    {"A":{"a":[{"B":{"b":[]}]}}
instead of:
    {"A":{"a":[{"B":{"b":[]}}]}}
The '}' closing the B object is missing.

Code sample producing the error:

```
class C{
public:
    string c;

    void serialize(JSON::Adapter& adapter){
        JSON::Class root(adapter, "C");
        JSON_T(adapter, c);
    }
};

class B{
public:
    vector<C> b;

    void serialize(JSON::Adapter& adapter){
        JSON::Class root(adapter, "B");
        JSON_T(adapter, b);
    }
};

class A{
public:
    vector<B> a;

    void serialize(JSON::Adapter& adapter){
        JSON::Class root(adapter, "A");
        JSON_T(adapter, a);
    }
};

int main(int argc, char** argv) {

    A a;
    a.a.push_back(B());
    cout << JSON::producer<A>::convert(a) << endl;

    return 0;
}
```

**Comment by g40** [comment]
Yes, thanks for the report. The generation for nesting does need to be a little smarter I think.

**Comment by btcinsight** [comment]
I created a pull request with a fix. Basically, the "(de)serializing vector" state was overwritten when (de)serializing nested vectors.

**Comment by g40** [comment]
Fixed, Many thanks.
