### ISSUE TITLE
Failed unit tests for DoubleConverter

### ISSUE THREAD

**Issue by massey101** [g40/esj#10]
Running unit tests shows both test_converter and test_conversion failing.

After investigating I noticed that DoubleConverter::Convert runs Chordia::toString(iv, digits) to convert the fractional part of the number (int64_t iv) to a string. However the function it calls is toString(int64_t value, int base = 10) when clearly the function that was meant to be called is toString(double value,double precision = 0.0001).
This results in the fractional part of the number being represented in binary and causing the unit tests to fail.

This issue was introduced recently by 301e17eda6fcdc3ce0ea361883db9a411dc2e13a

**Comment by massey101** [comment]
Note: This was introduce by 301e17eda6fcdc3ce0ea361883db9a411dc2e13a

**Comment by g40** [comment]
Ah. Thanks for the report. Let me check. Can you show unit test output? And which compiler are  you using?

**Comment by g40** [comment]
Confirmed. Will fix. Thank you.

**Comment by g40** [comment]
Hello Massey101. Please confirm https://github.com/g40/esj/commit/2fed8860b642b1508dd512604bfaa7da60e5aa63 works for you and I will close. Thanks again.

**Comment by massey101** [comment]
I can confirm that all unit tests pass due to 2fed886.

**Comment by g40** [comment]
Massey101. Thanks again.

**Comment by massey101** [comment]
You're welcome.
