### ISSUE TITLE
Vector of types with inner types

### ISSUE THREAD

**Issue by tustvold** [g40/esj#3]
Serializing a vector of types with inner types produces incorrect JSON:

The following code, for example :

<pre>
<code>
class F {
public:
    F() : element(4) {
        
    }
    
    void serialize(JSON::Adapter& adapter) {
        JSON::Class root(adapter,"F");
        JSON_T(adapter, element);
    }
protected:
    int element;
};

class E {
public:
    
    
    E() : element1(54) {
        
    }
    
    void serialize(JSON::Adapter& adapter) {
        JSON::Class root(adapter,"E");
        JSON_E(adapter, element1);
        JSON_T(adapter, element2);
    }
protected:
    int element1;
    F element2;
};

class D {
public:
    
    void serialize(JSON::Adapter& adapter) {
        JSON::Class root(adapter,"D");
        JSON_T(adapter, data);
    }
    
    std::vector<E> data;
};
</code>
</pre>

Produces

<code>
{"D":{"data":[{"E":{"element1":54,{"F":{"element":4}}}}]}}
</code>

Which has an extra { } around F":{"element":4}

**Comment by g40** [comment]
Hello Raphael,

Thanks for the report. Did you use the latest code when producing this error?

**Comment by tustvold** [comment]
I believe so - are you having trouble reproducing it?

**Comment by g40** [comment]
Not yet tried it! Thought this problem got fixed a day or so ago. Let me pull your PR.

**Comment by tustvold** [comment]
It is a related problem but I don't think it is the same. The previous bug concerned the _vector flag being cleared when it shouldn't have been (with a vector of vectors), whereas this concerns it being set when it shouldn't (inner type of type within vector).

My PR removes the problematic _vector and handles the brackets for vectors in a different way, fixing this problem.

**Comment by g40** [comment]
Sounds  ideal. I'm just going to pop your test case into the framework and see what gives.

**Comment by g40** [comment]
The `std::vector data;` is supposed to be a vector of E? i.e.

`std::vector<E> data;`

**Comment by tustvold** [comment]
Oh yes. Not sure how that got lost.

**Comment by g40** [comment]
Excellent. Thanks for the PR.
