### ISSUE TITLE
Not able to build source code on linux

### ISSUE THREAD

**Issue by ShadabAliDev** [g40/esj#5]
I am not able to build this source code on linux with gcc 4.3.
it gives me error as shown below:

./Stringifier/stringer.h:324: error: call of overloaded ‘abs(int64_t&)’ is ambiguous
/usr/include/c++/4.4/cmath:94: note: candidates are: double std::abs(double)
/usr/include/c++/4.4/cmath:98: note:                 float std::abs(float)
/usr/include/c++/4.4/cmath:102: note:                 long double std::abs(long double)
In file included from ../Stringifier/json_adapter.h:66,
                 from ../Stringifier/json_writer.h:59,
                 from ../Stringify.h:17,
                 from ../TestBBS.cpp:3:
../Stringifier/json_lexer.h: In function ‘void JSON::throw_if(JSON::ISource*, bool, std::string)’:
../Stringifier/json_lexer.h:227: error: expected primary-expression before ‘)’ token
../Stringifier/json_lexer.h: In function ‘void JSON::throw_if(bool, Chordia::stringer&)’:
../Stringifier/json_lexer.h:237: error: expected primary-expression before ‘)’ token
In file included from ../Stringifier/json_writer.h:59,
                 from ../Stringify.h:17,
                 from ../TestBBS.cpp:3:
../Stringifier/json_adapter.h: At global scope:
../Stringifier/json_adapter.h:260: error: ‘std::vector’ has not been declared
../Stringifier/json_adapter.h:260: error: expected ‘,’ or ‘...’ before ‘<’ token
../Stringifier/json_adapter.h: In function ‘void JSON::stream(JSON::Adapter&, const std::string&, int)’:
../Stringifier/json_adapter.h:269: error: ‘is_same’ is not a member of ‘std’
../Stringifier/json_adapter.h:269: error: expected primary-expression before ‘,’ token
../Stringifier/json_adapter.h:269: error: expected primary-expression before ‘>’ token
../Stringifier/json_adapter.h:269: error: ‘::value’ has not been declared
../Stringifier/json_adapter.h:270: error: ‘is_same’ is not a member of ‘std’
../Stringifier/json_adapter.h:270: error: expected primary-expression before ‘,’ token
../Stringifier/json_adapter.h:270: error: expected primary-expression before ‘>’ token
../Stringifier/json_adapter.h:270: error: ‘::value’ has not been declared
../Stringifier/json_adapter.h:271: error: ‘is_integral’ is not a member of ‘std’
../Stringifier/json_adapter.h:271: error: expected primary-expression before ‘>’ token
../Stringifier/json_adapter.h:271: error: ‘::value’ has not been declared
../Stringifier/json_adapter.h:272: error: ‘is_floating_point’ is not a member of ‘std’
../Stringifier/json_adapter.h:272: error: expected primary-expression before ‘>’ token
../Stringifier/json_adapter.h:272: error: ‘::value’ has not been declared
../Stringifier/json_adapter.h:276: error: ‘stream_primitives’ was not declared in this scope
../Stringifier/json_adapter.h:276: error: expected primary-expression before ‘>’ token
../Stringifier/json_adapter.h:276: error: ‘value’ was not declared in this scope
../Stringifier/json_adapter.h:276: error: ‘more’ was not declared in this scope
../Stringifier/json_adapter.h:280: error: ‘stream_classes’ was not declared in this scope
../Stringifier/json_adapter.h:280: error: expected primary-expression before ‘>’ token
../Stringifier/json_adapter.h:280: error: ‘value’ was not declared in this scope
../Stringifier/json_adapter.h:280: error: ‘more’ was not declared in this scope
../Stringifier/json_adapter.h: At global scope:
../Stringifier/json_adapter.h:294: error: ‘std::vector’ has not been declared
../Stringifier/json_adapter.h:294: error: expected ‘,’ or ‘...’ before ‘<’ token
../Stringifier/json_adapter.h: In function ‘void JSON::stream_primitives(JSON::Adapter&, const std::string&, int)’:
../Stringifier/json_adapter.h:296: error: ‘vector’ in namespace ‘std’ does not name a type
../Stringifier/json_adapter.h:296: error: expected unqualified-id before ‘<’ token
../Stringifier/json_adapter.h:302: error: ‘iterator_t’ was not declared in this scope
../Stringifier/json_adapter.h:302: error: expected ‘;’ before ‘it’
../Stringifier/json_adapter.h:303: error: ‘it’ was not declared in this scope
../Stringifier/json_adapter.h:303: error: ‘value’ was not declared in this scope
../Stringifier/json_adapter.h:316: error: ‘more’ was not declared in this scope
../Stringifier/json_adapter.h:344: error: ‘value’ was not declared in this scope
../Stringifier/json_adapter.h:349: error: ‘more’ was not declared in this scope
../Stringifier/json_adapter.h: At global scope:
../Stringifier/json_adapter.h:360: error: ‘std::vector’ has not been declared
../Stringifier/json_adapter.h:360: error: expected ‘,’ or ‘...’ before ‘<’ token
../Stringifier/json_adapter.h: In function ‘void JSON::stream_classes(JSON::Adapter&, const std::string&, int)’:
../Stringifier/json_adapter.h:362: error: ‘vector’ in namespace ‘std’ does not name a type
../Stringifier/json_adapter.h:362: error: expected unqualified-id before ‘<’ token
../Stringifier/json_adapter.h:368: error: ‘iterator_t’ was not declared in this scope
../Stringifier/json_adapter.h:368: error: expected ‘;’ before ‘it’
../Stringifier/json_adapter.h:369: error: ‘it’ was not declared in this scope
../Stringifier/json_adapter.h:369: error: ‘value’ was not declared in this scope
../Stringifier/json_adapter.h:386: error: ‘more’ was not declared in this scope
../Stringifier/json_adapter.h:417: error: ‘value’ was not declared in this scope
../Stringifier/json_adapter.h:422: error: ‘more’ was not declared in this scope

**Comment by g40** [comment]
Fixed in https://github.com/g40/esj/commit/843c90522dba3fa0ecb9387c499afbfd9b618526

N.B. You probably need a newer C++ compiler and use

`g++ -c -std=c++11 main.cpp` to compile

Please confirm and I will close. Thanks for the report.

**Comment by massey101** [comment]
According to the documentation c++11 isn't required. Is the documentation out of date or is this a valid issue?

**Comment by g40** [comment]
A very fair point. I will update the readme.

**Comment by massey101** [comment]
You might also want to update the info in doc/ and on http://www.codeproject.com/script/Articles/View.aspx?aid=856277
