### ISSUE TITLE
thread-safe

### ISSUE THREAD

**Issue by mr-ice** [g40/esj#8]
Can you make a statement about ESJ's thread safety?  I am interested in using it in a multi threaded application.

Thanks!

**Comment by g40** [comment]
Hello Michael and thanks for the interest. 

There are no synchronization mechanisms used in ESJ. So use in a threaded environment requires some care on the part of the producer/consumer. This will not be too onerous in most cases. Can you provide a little more detail of what you have in mind and I can qualify for you.
