### ISSUE TITLE
'int64_t' and 'long' type ambiguity on 'arm64v8'

### ISSUE THREAD

**Issue by cevarojetam** [g40/esj#9]
First of all, excellent project!

When building for _Android_ using NDK, the architecture **arm64v8**, both _gnu_ and _clang_ toolchains have a problem with overloading in **stringer.h**:

``` c++
inline std::string toString(long value, int base = 10)
```

and

``` c++
inline std::string toString(int64_t value, int base = 10)
```

```
clang: Error:(143, 24) redefinition of 'std::__1::string Chordia::toString(long int, int)'
gnu: Error:(143, 24) redefinition of 'std::string Chordia::toString(long int, int)'
```

What worked for me:

``` c++
#if LONG_MAX != LLONG_MAX
    inline std::string toString(long value, int base = 10)
    {
        return toString((int64_t)value,base);
    }
#endif
```

I'm using C++11 but trying to apply `std::enable_if`, which also normally works, brought me headache on Android.

**Comment by g40** [comment]
Thanks for the interest and kind comments. 

re the overloading issue. Which versions of GCC/Clang are in use? The macro test is certainly a viable solution though I wonder if there is another way ...

The std::enable_if is a surprise. Was this a problem for both compilers?

**Comment by massey101** [comment]
I am running on linux amd64 and also had this issue. Using the define fixed it for me.

**Comment by g40** [comment]
Thank you both. Closing.
